version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./project:/var/www/symfony
    expose:
      - "9000"
    environment:
      APP_ENV: dev

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - .:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"
    depends_on:
      - php

  postgres_db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}